spring.config.import=aws-parameterstore:${AWS_PARAMETERSTORE_PATH}

spring.datasource.url=jdbc:mysql://${DB_URL}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.sql.init.mode=never
spring.sql.init.platform=mysql


spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
spring.cloud.aws.s3.bucket=${AWS_S3_BUCKET_NAME}

spring.h2.console.enabled=false
