spring.application.name=nbc-cloud-assignment
spring.h2.console.enabled=false
spring.sql.init.mode=never

management.endpoints.web.exposure.include=health,info
management.info.env.enabled=true
info.app.name=nbc-cloud-assignment
info.app.description=Spring Boot application for NBC Cloud Assignment
info.app.version=1.0.15


spring.profiles.active=${PROFILE:prod}
